[project]
name = "shadertoytemplate"
version = "0.1.0"
description = "Python app using moderngl to create a template OpenGL canvas for shadertoy-type graphics"
requires-python = ">=3.12"
dependencies = [
    "moderngl>=5.12.0",
    "moderngl-window>=3.1.1",
]
